export const GET_CATEGORY_LIST_REQUEST = 'GET_CATEGORY_LIST_REQUEST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_ERROR = 'GET_CATEGORY_LIST_ERROR';

export const GET_CATEGORY_COURSE_LIST_REQUEST = 'GET_CATEGORY_COURSE_LIST_REQUEST';
export const GET_CATEGORY_COURSE_LIST_SUCCESS = 'GET_CATEGORY_COURSE_LIST_SUCCESS';
export const GET_CATEGORY_COURSE_LIST_ERROR = 'GET_CATEGORY_COURSE_LIST_ERROR';

export const GET_COURSE_DETAILS_REQUEST = 'GET_COURSE_DETAILS_REQUEST';
export const GET_COURSE_DETAILS_SUCCESS = 'GET_COURSE_DETAILS_SUCCESS';
export const GET_COURSE_DETAILS_ERROR = 'GET_COURSE_DETAILS_ERROR';

export const TOGGLE_SAVED_COURSE = "TOGGLE_SAVED_COURSE";
