export const ASYNC_REQUEST_INIT = 'ASYNC_REQUEST_INIT';
export const ASYNC_REQUEST_FAIL = 'ASYNC_REQUEST_FAIL';

export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_COURSE_LIST_SUCCESS = 'GET_CATEGORY_COURSE_LIST_SUCCESS';
export const GET_COURSE_DETAILS_SUCCESS = 'GET_COURSE_DETAILS_SUCCESS';

export const TOGGLE_SUBCATEGORIES = 'TOGGLE_SUBCATEGORIES';
