export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE';

export const GET_CATEGORY_COURSE_LIST = 'GET_CATEGORY_COURSE_LIST';
export const GET_CATEGORY_COURSE_LIST_SUCCESS = 'GET_CATEGORY_COURSE_LIST_SUCCESS';
export const GET_CATEGORY_COURSE_LIST_FAILURE = 'GET_CATEGORY_COURSE_LIST_FAILURE';

export const GET_COURSE_DETAILS = 'GET_COURSE_DETAILS';
export const GET_COURSE_DETAILS_SUCCESS = 'GET_COURSE_DETAILS_SUCCESS';
export const GET_COURSE_DETAILS_FAILURE = 'GET_COURSE_DETAILS_FAILURE';

export const SAVE_COURSE_SLUG = "SAVE_COURSE_SLUG";
